version: '3.8'

services:
  app:
    build: .
    container_name: go-bff
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    container_name: redis-cache
    restart: always

volumes:
  db_data:
